version: 2

defaults: &defaults
  steps:
  - checkout
  - run:
      name: Install deps
      command: |
        npm install
        ./node_modules/.bin/lerna bootstrap
  - run:
      name: Compile
      command: |
        ./node_modules/.bin/lerna run compile
  - run:
      name: Test core
      working_directory: packages/core
      environment:
      - JEST_JUNIT_OUTPUT: /app_root/test-results/core/results.xml
      command:
        npm test -- --ci --coverage --reporters="jest-junit" && cat ./coverage/lcov.info | ../../node_modules/.bin/coveralls

  - run:
      name: Test msgpack
      working_directory: packages/msgpack-adapter
      environment:
      - JEST_JUNIT_OUTPUT: /app_root/test-results/msgpack-adapter/results.xml
      command:
        npm test -- --ci --coverage --reporters="jest-junit" && cat ./coverage/lcov.info | ../../node_modules/.bin/coveralls

  - run:
      name: Test jest snapshot integration
      working_directory: packages/jest
      environment:
      - JEST_JUNIT_OUTPUT: /app_root/test-results/jest/results.xml
      command:
        npm test -- --ci --coverage --reporters="jest-junit" && cat ./coverage/lcov.info | ../../node_modules/.bin/coveralls

jobs:
  test_8:
    <<: *defaults
    docker:
    - image: node:8

  test_10:
    <<: *defaults
    docker:
    - image: node:10

  lint:
    docker:
    - image: node:10
    steps:
    - checkout
    - run:
        name: Install deps
        command: |
          npm install
    - run:
        name: Linter
        command: |
          ./node_modules/.bin/lerna run lint

workflows:
  version: 2
  main:
    jobs:
    - test_8
    - test_10
    - lint
